version: '3.4'
services:
  rstudio:
    image: rocker/rstudio 
    environment:
      - USER=${USER:-user}
      - PASSWORD=${PASSWORD:-password}
    networks:
      - traefik_traefik
    deploy:
      labels:
        - traefik.port=8787
        - traefik.frontend.rule=PathPrefixStrip:/${TRAEFIK_PREFIX:-rstudio}/

networks:
  traefik_traefik:
    external: true 

