version: "3.4"

services:
  tuleap:
    image: enalean/tuleap-aio
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST:-localhost}"
      DB_HOST: "db"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-ChangeMe}"
    volumes:
      - tuleap-data:/data
    ports:
      - 10080:80
    depends_on:
      - db

  db:
    image: mysql:5.6
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-ChangeMe}"

volumes:
  db-data:
  tuleap-data:
