version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      #- ./init:/docker-entrypoint-initdb.d
      - data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: guacamole_db
    networks:
      - guac
  postgresinit:
    image: postgres
    command: /bin/bash -c 'apt-get update && apt-get install -y curl && curl https://gist.githubusercontent.com/jmcarbo/ecda91233c6d4e94b4b963949cf759dd/raw/b70928f9cd1d22875c06b6a77075c1ce249bc707/guacamole.sql | psql -h postgres -U guacamole_user guacamole_db'
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: guacamole_db
      PGPASSWORD: some_password
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - postgres
    networks:
      - guac
  guacd:
    image: guacamole/guacd
    restart: always
    networks:
      - guac
  guac:
    image: guacamole/guacamole
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
    networks:
      - guac
    depends_on:
      - postgres
      - guacd
    
volumes:
  data:
    driver: local

networks:
  guac:
    driver: overlay
