version: '3.4'
services:
  elasticfake:
    image: python
    command: /bin/bash -c 'echo "$$INITBASH" | tee /initbash && /bin/bash /initbash'
    environment:
      INITBASH: |-
        #!/bin/bash
        pip install tornado
        curl https://raw.githubusercontent.com/oliver006/elasticsearch-test-data/master/es_test_data.py
        python es_test_data.py --es_url=${ELASTIC_URL:-http://localhost:9200}
