version: '3.4'
services:
  traefik:
    image: traefik:1.5-alpine
    command: --docker.swarmmode
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

networks:
  traefik:
    driver: overlay
    attachable: true

