version: '3.4'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    #image: bitnami/elasticsearch:latest
    environment:
      #- ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      #- ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch,elasticsearch2
      #- ELASTICSEARCH_NODE_NAME=elastic-node1
      #- ELASTICSEARCH_HEAP_SIZE=256
      #- ELASTIC_PASSWORD=MagicWord
      #- cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elastic-cluster
    #image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    container_name: elasticsearch
    ulimits:
      nproc: -1
      nofile:
        soft: -1
        hard: -1
      memlock:
        soft: -1
        hard: -1
    volumes:
      #- esdata1:/bitnami/elasticsearch
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    #image: bitnami/elasticsearch:latest
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    container_name: elasticsearch2
    environment:
      #- ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      #- ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch,elasticsearch2
      #- ELASTICSEARCH_NODE_NAME=elastic-node2
      #- ELASTICSEARCH_HEAP_SIZE=256
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elastic-cluster
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      #- ELASTIC_PASSWORD=MagicWord    
      #- cluster.name=docker-cluster
      #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - network.host=0.0.0.0
    ulimits:
      nproc: -1
      nofile:
        soft: -1
        hard: -1
      memlock:
        soft: -1
        hard: -1
    volumes:
      #- esdata1:/bitnami/elasticsearch
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.1
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch
      - elasticsearch2
      
networks:
  esnet:
    driver: overlay
    
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
